version: '3.9'
services:
  postgresdb:
    image: postgres:latest
    container_name: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=helper
      - DATABASE_HOST=postgresdb
    ports:
      - '1234:5432'
    networks:
      - learning
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6370:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    networks:
      - learning
  app:
    container_name: helper_backend
    tty: true
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - cache
      - postgresdb
    networks:
      - learning
volumes:
  cache:
## Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge