Name: helper

Log:
    Level: debug
    Format: json
    Development: true

HTTP:
    Host: 0.0.0.0
    Port: 8080

Database:
    Engine: postgres
    Name: helper
    Host: database-1.cypz2uzea0qm.ap-southeast-1.rds.amazonaws.com
    Port: 5432
    Username: postgres
    Password: MZterSfznMD4jkxbp01b
Cache:
    Host: redis-16349.c14.us-east-1-3.ec2.cloud.redislabs.com
    Port: 16349
    Password: lnoScC48AHSXHsTQWQuMGiU2qXT6KAW0
    Database: redis-iecom-backend-dev-11018383
JWT:
    Algorithm: HS256
    Key: secret
    Exp: 50000000
File:
    StoragePath: ./static