basePath: /
definitions:
  dto.ArticleDTO:
    properties:
      description:
        additionalProperties: true
        type: object
      enclosure:
        additionalProperties: true
        type: object
      guid:
        type: string
      link:
        items:
          type: string
        type: array
      pubDate:
        type: string
      title:
        type: string
    type: object
  dto.ChangePasswordRequest:
    properties:
      new_password:
        minLength: 8
        type: string
      old_password:
        type: string
    required:
    - new_password
    type: object
  dto.CreateMenuRequestDTO:
    properties:
      day_menus:
        items:
          $ref: '#/definitions/dto.DayMenuDTO'
        type: array
      description:
        type: string
      price:
        type: integer
      title:
        type: string
    type: object
  dto.CreateTransactionRequestDTO:
    properties:
      address:
        type: string
      amount:
        type: integer
      count:
        type: integer
      created_at:
        type: string
      end_date:
        type: string
      is_afternoon:
        type: boolean
      is_morning:
        type: boolean
      is_noon:
        type: boolean
      lat:
        type: number
      lng:
        type: number
      menu_id:
        type: integer
      start_date:
        type: string
      updated_at:
        type: string
      upload:
        type: string
      user_id:
        type: integer
    type: object
  dto.CreateUserRequestDTO:
    properties:
      address:
        type: string
      email:
        type: string
      image:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
      phone_number:
        type: string
    required:
    - email
    - name
    - password
    type: object
  dto.DayMenuDTO:
    properties:
      day:
        type: string
      image:
        type: string
      items:
        items:
          type: string
        type: array
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dto.UserDTO'
    type: object
  dto.MenuDTO:
    properties:
      day_menus:
        items:
          $ref: '#/definitions/dto.DayMenuDTO'
        type: array
      description:
        type: string
      id:
        type: integer
      price:
        type: integer
      title:
        type: string
    type: object
  dto.TransactionDTO:
    properties:
      address:
        type: string
      amount:
        type: integer
      count:
        type: integer
      created_at:
        type: string
      end_date:
        type: string
      id:
        type: integer
      is_afternoon:
        type: boolean
      is_morning:
        type: boolean
      is_noon:
        type: boolean
      lat:
        type: number
      lng:
        type: number
      menu:
        $ref: '#/definitions/dto.MenuDTO'
      menu_id:
        type: integer
      remaining:
        type: integer
      start_date:
        type: string
      status:
        type: string
      updated_at:
        type: string
      upload:
        type: string
      user_id:
        type: integer
    type: object
  dto.UpdateTransactionDTO:
    properties:
      id:
        type: integer
      status:
        type: string
      upload:
        type: string
    type: object
  dto.UpdateUserDTO:
    properties:
      address:
        type: string
      image:
        type: string
      is_admin:
        type: boolean
      phone_number:
        type: string
    type: object
  dto.UserDTO:
    properties:
      address:
        type: string
      email:
        type: string
      id:
        type: integer
      image:
        type: string
      isAdmin:
        type: boolean
      name:
        type: string
      phone_number:
        type: string
    type: object
  lib.Response:
    properties:
      data: {}
      message: {}
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Helper Backend
  version: "1.0"
paths:
  /api/v1/article/:
    get:
      consumes:
      - application/json
      description: Get all article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ArticleDTO'
            type: array
      summary: Get all article
      tags:
      - article
    post:
      consumes:
      - application/json
      description: Create a new article with the input paylod
      parameters:
      - description: create article
        in: body
        name: article_info
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ArticleDTO'
      summary: Create a new article
      tags:
      - article
  /api/v1/file/:
    post:
      consumes:
      - multipart/form-data
      description: Create file
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      - description: file folder
        in: formData
        name: folder
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create file
      tags:
      - file
  /api/v1/file/predict/:
    post:
      consumes:
      - multipart/form-data
      description: Predict image
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Predict image
      tags:
      - file
  /api/v1/menu/:
    delete:
      consumes:
      - application/json
      description: Delete menu by id
      parameters:
      - description: menu id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MenuDTO'
      summary: Delete menu by id
      tags:
      - menu
    get:
      consumes:
      - application/json
      description: Get all menu
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.MenuDTO'
            type: array
      summary: Get all menu
      tags:
      - menu
    post:
      consumes:
      - application/json
      description: Create a new menu with the input paylod
      parameters:
      - description: create menu
        in: body
        name: menu_info
        required: true
        schema:
          $ref: '#/definitions/dto.CreateMenuRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.MenuDTO'
      summary: Create a new menu
      tags:
      - menu
  /api/v1/recommendation/:
    get:
      consumes:
      - application/json
      description: Get all article
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.ArticleDTO'
            type: array
      summary: Get all article
      tags:
      - article
    post:
      consumes:
      - application/json
      description: Create a new article with the input paylod
      parameters:
      - description: create article
        in: body
        name: article_info
        required: true
        schema:
          $ref: '#/definitions/dto.ArticleDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ArticleDTO'
      summary: Create a new article
      tags:
      - article
  /api/v1/transaction/:
    get:
      consumes:
      - application/json
      description: Get all transaction
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.TransactionDTO'
            type: array
      summary: Get all transaction
      tags:
      - transaction
    patch:
      consumes:
      - application/json
      description: update transaction
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      - description: create transaction
        in: body
        name: transaction_info
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateTransactionDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dto.TransactionDTO'
            type: array
      summary: update transaction
      tags:
      - transaction
    post:
      consumes:
      - application/json
      description: Create a new transaction with the input paylod
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      - description: create transaction
        in: body
        name: transaction_info
        required: true
        schema:
          $ref: '#/definitions/dto.CreateTransactionRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TransactionDTO'
      summary: Create a new transaction
      tags:
      - transaction
  /api/v1/user/:
    get:
      consumes:
      - application/json
      description: Get User By ID
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.Response'
      summary: Get User By ID
      tags:
      - user
    patch:
      consumes:
      - application/json
      description: Update User
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      - description: update user
        in: body
        name: user_info
        required: true
        schema:
          $ref: '#/definitions/dto.UpdateUserDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.Response'
      summary: Update User
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Create a new user with the input paylod
      parameters:
      - description: create user
        in: body
        name: user_info
        required: true
        schema:
          $ref: '#/definitions/dto.CreateUserRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
      summary: Create a new user
      tags:
      - user
  /api/v1/user/info:
    get:
      consumes:
      - application/json
      description: Get User
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lib.Response'
      summary: Get User
      tags:
      - user
  /api/v1/user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: user login info
        in: body
        name: login_info
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
      summary: Login
      tags:
      - user
  /api/v1/user/password/change:
    post:
      consumes:
      - application/json
      description: Change Password
      parameters:
      - description: user token
        in: header
        name: Authorization
        required: true
        type: string
      - description: create user
        in: body
        name: user_info
        required: true
        schema:
          $ref: '#/definitions/dto.ChangePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserDTO'
      summary: Change Password
      tags:
      - user
swagger: "2.0"
